twig:
    file_name_pattern: "*.twig"
    default_path: "%kernel.project_dir%/templates"
    globals: {}
    date:
        timezone: "Europe/Paris"

when@test:
    twig:
        strict_variables: true
